version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    ports:
      - 5432:5432 # expose Postgres port

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      POSTGRES_SERVER_ADDR: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      PORT: 8080
   
    depends_on:
      - db # depends on Postgres service
    ports:
      - 8080:8080 # expose backend port

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    depends_on:
      - backend # depends on backend service
    environment:
      BACKEND_SERVER_ADDR: backend:8000
    ports:
      - 3000:3000 # expose frontend port

